// 1. Collection Names (to avoid typos later)
export const COLLECTIONS = {
  USERS: 'users',
  EXPENSES: 'expenses',
  BUDGETS: 'budgets', // or we might store this inside the user document
};

// 2. Predefined Categories (for the dropdown menu in Day 11)
export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transportation',
  'Housing & Bills',
  'Entertainment',
  'Shopping',
  'Health & Fitness',
  'Personal Care',
  'Education',
  'Travel',
  'Miscellaneous'
];

/**
 * @typedef {Object} UserProfile
 * @property {string} uid - The unique Firebase Auth ID
 * @property {string} email - User's email address
 * @property {string} displayName - User's full name
 * @property {string} photoURL - URL to profile picture
 * @property {string} createdAt - ISO Date string of account creation
 */

/**
 * @typedef {Object} Expense
 * @property {string} [id] - Unique ID (generated by Firestore)
 * @property {string} userId - Owner of the expense
 * @property {number} amount - The cost (positive number)
 * @property {string} category - One of EXPENSE_CATEGORIES
 * @property {string} description - Short text description
 * @property {string} date - ISO Date string (YYYY-MM-DD)
 * @property {string} createdAt - ISO Timestamp of entry creation
 */

/**
 * @typedef {Object} Budget
 * @property {string} userId - Owner of the budget
 * @property {string} month - Format "YYYY-MM" (e.g. "2024-01")
 * @property {number} limit - The maximum spending amount
 */


/**
 * Creates a standard Expense object ready for Firestore
 */
export const createExpenseModel = (userId, amount, category, description, date) => {
  return {
    userId,
    amount: parseFloat(amount), // Ensure it's a number
    category,
    description: description || 'No description',
    date,
    createdAt: new Date().toISOString()
  };
};

/**
 * Creates a standard User object
 */
export const createUserModel = (user) => {
  return {
    uid: user.uid,
    email: user.email,
    displayName: user.displayName || 'User',
    photoURL: user.photoURL || '',
    createdAt: new Date().toISOString()
  };
};